#' JsonCSVMaskr: deterministic masking for JSON and CSV data
#'
#' JsonCSVMaskr is an R translation of the PowerShell Flat & Mask data masking
#' tool. It masks selected CSV columns or JSON field paths with deterministic
#' HMAC-SHA256 values, writes a masking key, preserves a masked JSON copy when
#' applicable, normalizes nested JSON into related CSV tables, and includes a
#' Shiny interface.
#'
#' @section Supported input shapes:
#' CSV files with headers; ordinary JSON objects; arrays of JSON objects;
#' NDJSON, JSON Lines, comma-separated loose objects, and concatenated objects;
#' Socrata exports with `meta.view.columns` and row-array `data`; GeoJSON
#' `FeatureCollection` objects; envelope collections under `data`, `results`,
#' `items`, or `records`; and top-level header-row array JSON.
#'
#' @section Masking behavior:
#' Masked values are the first 12 Base64 characters of an HMAC-SHA256 digest of
#' the original value using the supplied secret key. The same original value and
#' key always produce the same masked value. Empty values remain empty.
#'
#' @keywords internal
#' @importFrom digest digest hmac
#' @importFrom jsonlite base64_enc fromJSON toJSON
#' @importFrom shiny actionButton br checkboxGroupInput column fileInput fluidPage h3 h4 hr observe observeEvent passwordInput reactiveVal renderText runApp shinyApp sidebarLayout sidebarPanel tagList tags textInput uiOutput
#' @importFrom stats setNames
#' @importFrom tools file_ext
#' @importFrom utils count.fields read.csv read.table tail
#' @rawNamespace export(add_estimated_table_names_from_object)
#' @rawNamespace export(add_gui_log_line)
#' @rawNamespace export(add_json_object_array_counts)
#' @rawNamespace export(add_mapping_row)
#' @rawNamespace export(apply_masking_to_object)
#' @rawNamespace export(complete_masking_outputs)
#' @rawNamespace export(convert_header_array_rows_to_objects)
#' @rawNamespace export(convert_rows_for_csv_export)
#' @rawNamespace export(convert_to_app_version)
#' @rawNamespace export(convert_to_csv_line)
#' @rawNamespace export(count_maskable_fields_in_object)
#' @rawNamespace export(datamaskr)
#' @rawNamespace export(export_masking_key)
#' @rawNamespace export(export_replication_tool_source)
#' @rawNamespace export(format_status_line)
#' @rawNamespace export(generate_replication_script)
#' @rawNamespace export(get_csv_fields)
#' @rawNamespace export(get_json_fields)
#' @rawNamespace export(get_json_progress_target)
#' @rawNamespace export(get_json_record_collection_info)
#' @rawNamespace export(get_job_progress_detail)
#' @rawNamespace export(get_masked_value)
#' @rawNamespace export(get_replication_tool_source_text)
#' @rawNamespace export(get_selected_field_set)
#' @rawNamespace export(get_socrata_columns)
#' @rawNamespace export(get_socrata_json_fields)
#' @rawNamespace export(get_table_name_from_path)
#' @rawNamespace export(get_tool_update_status)
#' @rawNamespace export(get_visible_json_properties)
#' @rawNamespace export(invoke_csv_masking_fast)
#' @rawNamespace export(invoke_header_array_json_masking)
#' @rawNamespace export(invoke_json_records_masking)
#' @rawNamespace export(invoke_masking)
#' @rawNamespace export(invoke_socrata_json_masking)
#' @rawNamespace export(jsoncsvmaskr_app)
#' @rawNamespace export(mask_if_needed)
#' @rawNamespace export(new_table_row_id)
#' @rawNamespace export(normalize_field_name)
#' @rawNamespace export(process_masked_object)
#' @rawNamespace export(read_json_file_with_load_progress)
#' @rawNamespace export(read_loose_json_records)
#' @rawNamespace export(read_text_file_with_load_progress)
#' @rawNamespace export(reset_job_estimate)
#' @rawNamespace export(run_app)
#' @rawNamespace export(run_datamaskr)
#' @rawNamespace export(set_csv_job_estimate)
#' @rawNamespace export(set_job_estimate)
#' @rawNamespace export(set_json_object_job_estimate)
#' @rawNamespace export(set_json_record_job_estimate)
#' @rawNamespace export(set_progress_record_target)
#' @rawNamespace export(should_mask_field)
#' @rawNamespace export(sync_table_estimate_with_produced)
#' @rawNamespace export(test_estimate_field_match)
#' @rawNamespace export(test_header_array_json)
#' @rawNamespace export(test_socrata_json)
#' @rawNamespace export(update_processing_progress)
#' @rawNamespace export(write_job_estimate_status)
#' @rawNamespace export(write_mask_log)
#' @rawNamespace export(write_status_panel)
#' @rawNamespace export(write_verbose_log)
"_PACKAGE"

#' Run a complete masking job
#'
#' `datamaskr()` is the primary scripted interface. It resets package state,
#' detects whether the input is CSV or one of the supported JSON shapes, masks
#' selected fields, writes output files, and mirrors progress through console
#' status messages or an optional callback.
#'
#' `invoke_masking()` is retained as a compatibility alias for replication
#' scripts generated by earlier versions of JsonCSVMaskr and the original
#' PowerShell tool.
#'
#' @param input_file Path to a `.csv` or `.json` file.
#' @param output_folder Directory where output files should be written.
#' @param key_file Path for the masking key CSV. Defaults to
#'   `masking_key.csv` inside `output_folder`.
#' @param secret_key Secret key used as the HMAC-SHA256 key. Reusing the same
#'   key with the same input value gives the same masked value.
#' @param mask_fields Character vector of CSV column names or JSON field paths
#'   to mask. JSON paths may include or omit the `root.` prefix.
#' @param progress_callback Optional function called as
#'   `progress_callback(stage, current, total, message)`, where `stage` is one
#'   of `"load"`, `"mask"`, `"normalize"`, or `"export"`.
#'
#' @return Invisibly returns `output_folder`. Files are written for their side
#'   effects. CSV jobs write `data.csv`, `masking_key.csv`, and
#'   `replicate_masking.R`. JSON jobs also write a masked JSON/NDJSON file and
#'   normalized CSV tables.
#'
#' @examples
#' input <- tempfile(fileext = ".csv")
#' writeLines(c("name,email", "Alice,alice@example.com"), input)
#' out <- tempfile()
#' datamaskr(input, out, secret_key = "demo", mask_fields = "email")
#' list.files(out)
#'
#' @seealso [json_helpers], [csv_helpers], [shiny_app]
#' @name datamaskr
#' @aliases invoke_masking
#' @usage
#' datamaskr(input_file, output_folder,
#'   key_file = file.path(output_folder, "masking_key.csv"),
#'   secret_key, mask_fields, progress_callback = NULL)
#'
#' invoke_masking(input_file, output_folder,
#'   key_file = file.path(output_folder, "masking_key.csv"),
#'   secret_key, mask_fields, progress_callback = NULL)
NULL

#' Deterministic masking primitives
#'
#' Helpers that mirror the masking functions in `DataMaskingTool.ps1`.
#'
#' @param value,Value Scalar value to hash. Empty or missing values return an
#'   empty string.
#' @param key,Key Secret HMAC key.
#' @param field_path,FieldPath,FieldName Field path such as `root.email`.
#' @param mask_fields,MaskFields Character vector of fields selected for masking.
#' @param selected_field_set Normalized field set returned by
#'   `get_selected_field_set()`.
#' @param original,Original Original unmasked value.
#' @param masked,Masked Masked value.
#' @param field,Field Normalized field name.
#' @param row_index,RowIndex Optional zero-based source row index.
#' @param object,Object R list representing a JSON object or array.
#' @param prefix,Prefix Current JSON path prefix.
#'
#' @return `get_masked_value()` returns a 12-character deterministic mask.
#'   Field-selection helpers return logical values or normalized character
#'   vectors. Object functions return masked R objects or update internal
#'   state used by a masking run.
#'
#' @examples
#' get_masked_value("alice@example.com", "secret")
#' normalize_field_name("root.person.email")
#'
#' @name masking_helpers
#' @aliases get_selected_field_set test_estimate_field_match normalize_field_name
#' @aliases should_mask_field get_masked_value add_mapping_row mask_if_needed
#' @aliases apply_masking_to_object get_table_name_from_path new_table_row_id
#' @aliases process_masked_object convert_rows_for_csv_export
NULL

#' JSON parsing, discovery, and shape detection helpers
#'
#' Functions for reading supported JSON inputs, discovering selectable field
#' paths, detecting special JSON table formats, and estimating JSON work size.
#'
#' @param file_path,FilePath,path,Path Path to a JSON file.
#' @param json,Json Parsed JSON value as nested R lists.
#' @param records,Records List of JSON records.
#' @param rows,Rows Header-array JSON rows or rows to normalize.
#' @param object,Object Nested R list or scalar.
#' @param table_names,TableNames Environment used to collect table names.
#' @param table_name,TableName Current normalized table name.
#' @param counts,Counts Environment used to count array/object records.
#' @param mode_name,ModeName Human-readable mode name for progress messages.
#' @param mask_fields,MaskFields Character vector of selected fields.
#' @param selected_field_set Normalized selected-field vector.
#' @param prefix,Prefix Current JSON path prefix.
#' @param start_percent,end_percent Progress range used while reading text.
#'
#' @return Parsed JSON records, character vectors of field paths, logical
#'   detection values, table/record metadata lists, or invisible updates to job
#'   estimate state.
#'
#' @examples
#' input <- tempfile(fileext = ".json")
#' writeLines('{"person":{"email":"a@example.com"}}', input)
#' get_json_fields(input)
#'
#' @name json_helpers
#' @aliases read_text_file_with_load_progress read_json_file_with_load_progress
#' @aliases count_maskable_fields_in_object add_estimated_table_names_from_object
#' @aliases set_json_record_job_estimate add_json_object_array_counts
#' @aliases get_json_progress_target set_json_object_job_estimate
#' @aliases test_socrata_json get_socrata_columns get_socrata_json_fields
#' @aliases get_visible_json_properties get_json_record_collection_info
#' @aliases test_header_array_json convert_header_array_rows_to_objects
#' @aliases read_loose_json_records get_json_fields
NULL

#' CSV helpers
#'
#' Functions for CSV field discovery, CSV job estimation, and CSV line quoting.
#'
#' @param file_path,FilePath,input_file,InputFile Path to a CSV file.
#' @param mask_fields,MaskFields Character vector of selected columns.
#' @param row_count,RowCount Number of data rows in the input.
#' @param values,Values Values to encode as one CSV line.
#'
#' @return `get_csv_fields()` returns a character vector of headers.
#'   `convert_to_csv_line()` returns a quoted CSV line. Estimation functions
#'   update internal progress state invisibly.
#'
#' @examples
#' input <- tempfile(fileext = ".csv")
#' writeLines(c("a,b", "1,2"), input)
#' get_csv_fields(input)
#'
#' @name csv_helpers
#' @aliases set_csv_job_estimate get_csv_fields convert_to_csv_line
NULL

#' Masking pipeline functions
#'
#' Lower-level processors for individual input families. These are exported to
#' mirror the PowerShell sub-functions, but most users should call
#' `datamaskr()` instead.
#'
#' @param input_file,InputFile Path to the source file.
#' @param output_folder,OutputFolder Output directory.
#' @param key_file,KeyFile Path for `masking_key.csv`.
#' @param secret_key,SecretKey HMAC secret key.
#' @param mask_fields,MaskFields Character vector of fields to mask.
#' @param records,Records List of JSON records.
#' @param json,Json Parsed JSON object.
#' @param mode_name,ModeName Human-readable processing mode.
#' @param output_format,OutputFormat `"JsonArray"` or `"Ndjson"`.
#'
#' @return Invisibly returns output paths or directories after writing masked
#'   artifacts.
#'
#' @name pipeline_helpers
#' @aliases invoke_json_records_masking invoke_header_array_json_masking
#' @aliases invoke_socrata_json_masking invoke_csv_masking_fast
NULL

#' Output and replication helpers
#'
#' Functions that export normalized CSV tables, masking keys, and replication
#' scripts after a masking run.
#'
#' @param output_folder,OutputFolder Directory where artifacts should be written.
#' @param key_file,KeyFile Path for the masking key CSV.
#' @param input_file,InputFile Source input path to embed in replication scripts.
#' @param secret_key,SecretKey HMAC secret key.
#' @param mask_fields,MaskFields Selected fields to embed in replication scripts.
#' @param skip_replication_script Logical; when `TRUE`, do not write
#'   `replicate_masking.R`.
#' @param version_text,VersionText Version string to parse.
#'
#' @return Paths to exported files, status lists, parsed package versions, or
#'   invisible completion values.
#'
#' @name export_helpers
#' @aliases complete_masking_outputs export_masking_key
#' @aliases get_replication_tool_source_text export_replication_tool_source
#' @aliases generate_replication_script convert_to_app_version
#' @aliases get_tool_update_status
NULL

#' Progress and status helpers
#'
#' Console and Shiny-log helpers that mirror the staged PowerShell progress
#' model: load, mask, normalize, and export.
#'
#' @param text,Text Text to format for console display.
#' @param width Console width.
#' @param message,Message Log message.
#' @param mode,Mode Status mode label.
#' @param phase,Phase Status phase label.
#' @param current,Current Current progress count.
#' @param total,Total Total progress count.
#' @param detail,Detail Additional detail text.
#' @param mask,Mask Masking event text.
#' @param force,Force Whether to force immediate status output.
#' @param rows,Rows Estimated rows.
#' @param fields,Fields Estimated fields.
#' @param tables,Tables Estimated tables.
#' @param method,Method Estimate method description.
#' @param path,Path Progress target path.
#' @param label,Label Progress target label.
#'
#' @return Status helpers update internal state and return invisibly unless
#'   otherwise noted. `format_status_line()` returns padded or truncated text.
#'
#' @name progress_helpers
#' @aliases format_status_line add_gui_log_line write_status_panel
#' @aliases write_verbose_log write_mask_log update_processing_progress
#' @aliases reset_job_estimate set_job_estimate sync_table_estimate_with_produced
#' @aliases get_job_progress_detail write_job_estimate_status
#' @aliases set_progress_record_target
NULL

#' Shiny application
#'
#' Build or launch the JsonCSVMaskr Shiny GUI. The app exposes the same workflow
#' as the PowerShell GUI: choose an input file, select fields, provide a secret
#' key, run masking, and monitor load/mask/normalize/export progress with a
#' console-style log.
#'
#' @param ... Arguments passed to [shiny::runApp()], such as `host`, `port`, or
#'   `launch.browser`.
#'
#' @return `jsoncsvmaskr_app()` returns a Shiny app object.
#'   `run_datamaskr()` launches it and returns when the Shiny process exits.
#'   `run_app()` is retained as a compatibility alias.
#'
#' @examples
#' app <- jsoncsvmaskr_app()
#' \dontrun{run_datamaskr(port = 3847)}
#'
#' @name shiny_app
#' @aliases jsoncsvmaskr_app run_datamaskr run_app
NULL
